name: 'BD CI Auto-Remediation'
description: 'CI orchestration layer using bd (beads) for automatic failure tracking, fix bead creation, and agent-driven remediation'
author: 'poiley'

branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  mode:
    description: 'Action mode: sync (sync beads state), create (create/reopen fix bead), cleanup (close fix beads for passed gate)'
    required: false
    default: 'create'

  # Failure details (for mode=create)
  failure-type:
    description: 'Type of failure: test_failure | coverage_gap | lint_error | build_error'
    required: false
  failure-summary:
    description: 'Brief summary of failures'
    required: false
  failure-details-file:
    description: 'Path to file with detailed failure output'
    required: false

  # Bead identification
  parent-bead-id:
    description: 'Parent bead ID (auto-detected if not provided)'
    required: false
  pr-number:
    description: 'Pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}

  # Configuration overrides
  assign-to-pr-author:
    description: 'Assign fix bead to PR author (true/false)'
    required: false
    default: 'true'
  fix-bead-priority:
    description: 'Priority for fix bead (0-4, 0=highest)'
    required: false
    default: '1'
  block-parent:
    description: 'Mark parent bead as blocked via blocking dependency (true/false)'
    required: false
    default: 'true'
  skip-if-no-parent:
    description: 'Skip gracefully if no parent bead found (true/false)'
    required: false
    default: 'true'

  # Git configuration
  sync-branch:
    description: 'Git branch for beads sync'
    required: false
    default: 'beads-sync'

  # BD CLI configuration
  bd-version:
    description: 'BD CLI version (latest or specific tag like v0.49.6)'
    required: false
    default: 'latest'

  # GitHub configuration
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  fix-bead-id:
    description: 'ID of the created/reopened fix bead (mode=create only)'
    value: ${{ steps.create-bead.outputs.bead-id }}
  parent-bead-id:
    description: 'ID of the parent bead'
    value: ${{ steps.detect-parent.outputs.bead-id }}
  skipped:
    description: 'true if remediation was skipped'
    value: ${{ steps.result-sync.outputs.skipped || steps.result-skipped.outputs.skipped || steps.result-final.outputs.skipped || 'true' }}

runs:
  using: 'composite'
  steps:
    # --- VALIDATION ---
    - name: Validate inputs
      shell: bash
      run: |
        if [ "${{ inputs.mode }}" = "create" ]; then
          if [ -z "${{ inputs.failure-type }}" ]; then
            echo "::error::failure-type is required for mode=create"
            exit 1
          fi
        fi
        if [ "${{ inputs.mode }}" = "cleanup" ]; then
          if [ -z "${{ inputs.failure-type }}" ]; then
            echo "::warning::failure-type not set for cleanup mode - will close ALL fix beads for parent"
          fi
        fi

    - name: Check for .beads directory
      if: inputs.mode != 'sync'
      shell: bash
      run: |
        if [ ! -d ".beads" ]; then
          echo "::error::No .beads directory found. Is bd initialized in this repo?"
          exit 1
        fi

    # --- INSTALL BD ---
    - name: Install bd CLI
      shell: bash
      env:
        BD_VERSION: ${{ inputs.bd-version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/scripts/install-bd.sh

    # --- SYNC MODE ---
    - name: Sync beads state
      if: inputs.mode == 'sync'
      shell: bash
      env:
        SYNC_BRANCH: ${{ inputs.sync-branch }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/scripts/sync-beads.sh

    - name: Set sync result
      if: inputs.mode == 'sync'
      id: result-sync
      shell: bash
      run: echo "skipped=false" >> "$GITHUB_OUTPUT"

    # --- IMPORT BEADS STATE (must run before detect-parent so bd show works) ---
    - name: Import beads state
      if: inputs.mode != 'sync'
      shell: bash
      env:
        SYNC_BRANCH: ${{ inputs.sync-branch }}
      run: |
        echo "::group::Importing beads state"
        git fetch origin "$SYNC_BRANCH" 2>/dev/null || true
        git show "origin/$SYNC_BRANCH:.beads/issues.jsonl" > .beads/issues.jsonl 2>/dev/null || touch .beads/issues.jsonl
        # Import JSONL into the bd database so bd show/list/update commands work.
        # Writing the file alone is not enough — bd reads from its SQLite database,
        # not from the JSONL file directly.
        if [ -s .beads/issues.jsonl ]; then
          bd import -i .beads/issues.jsonl --no-daemon 2>/dev/null || {
            echo "::warning::bd import failed, falling back to --no-db mode for subsequent commands"
          }
        fi
        echo "✅ Imported beads state from $SYNC_BRANCH"
        echo "::endgroup::"

    # --- DETECT PARENT (create/cleanup modes) ---
    - name: Detect parent bead ID
      if: inputs.mode != 'sync'
      id: detect-parent
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        PARENT_BEAD_ID: ${{ inputs.parent-bead-id }}
        SKIP_IF_NO_PARENT: ${{ inputs.skip-if-no-parent }}
      run: ${{ github.action_path }}/scripts/extract-bead-id.sh

    - name: Set skipped result
      if: inputs.mode != 'sync' && steps.detect-parent.outputs.skipped == 'true'
      id: result-skipped
      shell: bash
      run: |
        echo "skipped=true" >> "$GITHUB_OUTPUT"
        echo "::notice::Skipping remediation (no parent bead found)"

    # --- PARSE FAILURES (create mode) ---
    - name: Get PR branch
      if: inputs.mode == 'create' && steps.detect-parent.outputs.skipped != 'true'
      id: pr-info
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        PR_BRANCH=$(gh pr view "$PR_NUMBER" --json headRefName -q '.headRefName' 2>/dev/null || echo "")
        echo "branch=$PR_BRANCH" >> "$GITHUB_OUTPUT"

    - name: Parse failure details
      if: inputs.mode == 'create' && steps.detect-parent.outputs.skipped != 'true'
      id: parse-failures
      shell: bash
      env:
        FAILURE_TYPE: ${{ inputs.failure-type }}
        FAILURE_SUMMARY: ${{ inputs.failure-summary }}
        FAILURE_DETAILS_FILE: ${{ inputs.failure-details-file }}
        PR_NUMBER: ${{ inputs.pr-number }}
        PR_BRANCH: ${{ steps.pr-info.outputs.branch }}
        CI_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        case "$FAILURE_TYPE" in
          test_failure)    ${{ github.action_path }}/scripts/parse-test-failures.sh ;;
          coverage_gap)    ${{ github.action_path }}/scripts/parse-coverage-gaps.sh ;;
          lint_error)      ${{ github.action_path }}/scripts/parse-lint-errors.sh ;;
          build_error)     ${{ github.action_path }}/scripts/parse-build-errors.sh ;;
          *)
            echo "::warning::Unknown failure type: $FAILURE_TYPE"
            echo "summary=${FAILURE_SUMMARY:-CI failure}" >> "$GITHUB_OUTPUT"
            echo "metadata-file=" >> "$GITHUB_OUTPUT"
            ;;
        esac

    # --- CREATE/REOPEN FIX BEAD ---
    - name: Create or reopen fix bead
      if: inputs.mode == 'create' && steps.detect-parent.outputs.skipped != 'true'
      id: create-bead
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PARENT_BEAD_ID: ${{ steps.detect-parent.outputs.bead-id }}
        FAILURE_TYPE: ${{ inputs.failure-type }}
        FAILURE_SUMMARY: ${{ steps.parse-failures.outputs.summary }}
        METADATA_FILE: ${{ steps.parse-failures.outputs.metadata-file }}
        CI_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        ASSIGN_TO_PR_AUTHOR: ${{ inputs.assign-to-pr-author }}
        FIX_BEAD_PRIORITY: ${{ inputs.fix-bead-priority }}
        BLOCK_PARENT: ${{ inputs.block-parent }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: ${{ github.action_path }}/scripts/create-fix-bead.sh

    # --- CLEANUP FIX BEADS ---
    - name: Cleanup fix beads
      if: inputs.mode == 'cleanup' && steps.detect-parent.outputs.skipped != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        BEAD_ID: ${{ steps.detect-parent.outputs.bead-id }}
        FAILURE_TYPE: ${{ inputs.failure-type }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: ${{ github.action_path }}/scripts/cleanup-beads.sh

    # --- SYNC BACK TO GIT ---
    - name: Sync beads to git
      if: inputs.mode != 'sync' && steps.detect-parent.outputs.skipped != 'true'
      shell: bash
      env:
        SYNC_BRANCH: ${{ inputs.sync-branch }}
        MODE: ${{ inputs.mode }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        echo "::group::Syncing beads to git"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Export bd state to JSONL
        bd sync --no-db --no-daemon 2>/dev/null || true

        # Check if JSONL changed
        if git diff --quiet .beads/issues.jsonl 2>/dev/null; then
          echo "No beads changes to sync"
          echo "::endgroup::"
          exit 0
        fi

        # Save current HEAD
        CURRENT_SHA=$(git rev-parse HEAD)

        # Switch to sync branch
        git fetch origin "$SYNC_BRANCH" 2>/dev/null || true
        git checkout "origin/$SYNC_BRANCH" 2>/dev/null || git checkout --orphan "$SYNC_BRANCH"

        # Copy the updated JSONL
        mkdir -p .beads
        git checkout "$CURRENT_SHA" -- .beads/issues.jsonl 2>/dev/null || true

        # Commit
        git add -f .beads/issues.jsonl
        if [ "$MODE" = "create" ]; then
          COMMIT_MSG="CI auto-remediation: fix bead for PR #$PR_NUMBER"
        else
          COMMIT_MSG="CI auto-remediation: cleanup fix beads for PR #$PR_NUMBER"
        fi
        git commit -m "$COMMIT_MSG" || {
          echo "No changes to commit"
          git checkout "$CURRENT_SHA"
          echo "::endgroup::"
          exit 0
        }

        # Push with retry for race conditions
        for attempt in 1 2 3; do
          if git push origin HEAD:"$SYNC_BRANCH" 2>/dev/null; then
            echo "✅ Beads synced to $SYNC_BRANCH"
            break
          fi
          echo "Push attempt $attempt failed, pulling and retrying..."
          git pull --rebase origin "$SYNC_BRANCH" 2>/dev/null || true
        done

        # Return to original ref
        git checkout "$CURRENT_SHA" 2>/dev/null || true

        echo "::endgroup::"

    # --- FINAL RESULT ---
    - name: Set final result
      if: inputs.mode != 'sync' && steps.detect-parent.outputs.skipped != 'true'
      id: result-final
      shell: bash
      run: echo "skipped=false" >> "$GITHUB_OUTPUT"
