name: Lint with Auto-Remediation

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint run --out-format=line-number > lint-results.txt 2>&1 || true

      - name: Check lint results
        run: |
          if [ -s lint-results.txt ]; then
            echo "Lint errors found"
            cat lint-results.txt
            exit 1
          fi

      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: lint-results.txt

  create-fix-bead:
    name: Create Fix Bead
    if: failure() && github.event_name == 'pull_request'
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download lint results
        uses: actions/download-artifact@v4
        with:
          name: lint-results

      - uses: poiley/bdgha@v1
        with:
          mode: create
          failure-type: lint_error
          failure-summary: "Lint violations found"
          failure-details-file: lint-results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-fix-beads:
    name: Cleanup Fix Beads
    if: success() && github.event_name == 'pull_request'
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: poiley/bdgha@v1
        with:
          mode: cleanup
          github-token: ${{ secrets.GITHUB_TOKEN }}
